CREATE TABLE Building (
	ID_Building INT PRIMARY KEY,
	Statee VARCHAR(20) NOT NULL,
	City VARCHAR(30) NOT NULL,
	District VARCHAR(20) NOT NULL,
	Street VARCHAR(30) NOT NULL,
	BuildingNumber INT NOT NULL
);

CREATE TABLE Flat (
	ID_Flat INT PRIMARY KEY,
	FK_Building INT NOT NULL REFERENCES Building ON DELETE CASCADE ON UPDATE CASCADE,
	Size INT NOT NULL,
	Floorr INT NOT NULL,
	EnterGateSymbol CHAR(1) NOT NULL,
	FlatNumber INT NOT NULL
);

CREATE TABLE Subcontractor (
	RFC CHAR(10) PRIMARY KEY,
	Name VARCHAR(25) NOT NULL,
	Typee VARCHAR(20) NOT NULL
);

CREATE TABLE Build (
	FK_Subcontractor CHAR(10) NOT NULL REFERENCES Subcontractor ON DELETE CASCADE ON UPDATE CASCADE,
	FK_Building INT NOT NULL REFERENCES Building ON DELETE CASCADE ON UPDATE CASCADE,
	StartDate DATE NOT NULL,
	PlanEndDate DATE NOT NULL,
	EndDate DATE NOT NULL,

	PRIMARY KEY(FK_Subcontractor, FK_Building)
);

CREATE TABLE Equipment (
	ID_Equipment INT PRIMARY KEY,
	FK_Flat INT NOT NULL REFERENCES Flat ON DELETE CASCADE ON UPDATE CASCADE,
	Typee VARCHAR(20) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	PurchaseDate DATE NOT NULL,
	Price DECIMAL(7,2) NOT NULL
);

CREATE TABLE Agreement (
	ID_Agreement INT PRIMARY KEY,
	FK_Flat INT NOT NULL REFERENCES Flat ON DELETE CASCADE ON UPDATE CASCADE,
	Rent DECIMAL(7, 2) NOT NULL,
	PaymentDay INT NOT NULL,
	SignDate DATE NOT NULL,
	ReceptionDate DATE NOT NULL,
	EndDate DATE NOT NULL
); 

CREATE TABLE Person (
	CURP CHAR(11) PRIMARY KEY,
	Name VARCHAR(15) NOT NULL,
	SecendName VARCHAR(15) NOT NULL,
	Surname VARCHAR(25) NOT NULL,
	Sitee VARCHAR(11) NOT NULL
);

CREATE TABLE AgreementSign (
	FK_Agreement INT NOT NULL REFERENCES Agreement ON DELETE CASCADE ON UPDATE CASCADE,
	FK_Person CHAR(11) NOT NULL REFERENCES Person ON DELETE CASCADE ON UPDATE CASCADE,

	PRIMARY KEY(FK_Agreement, FK_Person)
);

CREATE TABLE Denunciation (
	ID_Denunciation INT PRIMARY KEY,
	FK_Agreement INT NOT NULL REFERENCES Agreement ON DELETE CASCADE ON UPDATE CASCADE,
	Datee DATE NOT NULL,
	Aplicant VARCHAR(11) NOT NULL,
	Reason VARCHAR(128) NOT NULL
); 

CREATE TABLE Payment (
	ID_Payment INT PRIMARY KEY,
	FK_Agreement INT NOT NULL REFERENCES Agreement ON DELETE CASCADE ON UPDATE CASCADE,
	Datee DATE NOT NULL,
	Amount DECIMAL(7, 2) NOT NULL
);